// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    attributes: {
      content: {
        type: 'string',
        required: true,
        minLength: 3
      }
    }
  };

}).call(this);

/*
//@ sourceMappingURL=Todo.map
*/
